#!/bin/bash

sudo mkdir -p /tmp/qamenu
cd /tmp/qemu

HEIGHT=10
WIDTH=40
CHOICE_HEIGHT=3
BACKTITLE="Uninstall QAMenu"
TITLE="Which dependencies should I keep?"
MENU="Choose one of the following options:"

OPTIONS=(1 "Remove all dependencies"
         2 "Keep basic dependencies"
         3 "Keep all dependencies")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            sudo curl -Ss -O http://qamenu-downloads.minejaj.cloud:20084/builds/release/uninstaller/remove/all && sudo sh all
            ;;
        2)
            sudo curl -Ss -O http://qamenu-downloads.minejaj.cloud:20084/builds/release/uninstaller/remove/basic && sudo sh basic
            ;;
        3)
            sudo curl -Ss -O http://qamenu-downloads.minejaj.cloud:20084/builds/release/uninstaller/remove/keep && sudo sh keep
            ;;
esac
